#+title: My German course
#+date: <2024-07-04 13:36>
#+description: This post records my impression for my German course
#+filetags: personal german


* Was ist passiert

Ich habe seit diesem Montag einen intensiven Deutschkurs gemacht.
Die Kurs fangt von 8:30 Uhr bis 11:45 Uhr jeden Tag an.
Weil von mein Wohnung bis zu die Schule ich fast einen Stunden brauche, muss ich vor 7 aufstehen und zur Bushaltstelle runnen.
Nach dem Kurs fahre ich mit dem Bus zur Buro und arbeite ich bis zum Abendessen.
Danach komme ich nach Haus zuruck und mache ein paar Haushalt.
Ich gehe circa 11 Uhr ins Bett.


* Ich kann kein gutes Englisch schreiben

Wenn ich hier diesen Satzen schreibe, merke ich, dass ich komplexe Satze auf Englisch nicht mehr schreiben kann.

This is interesting, I am still in the starting phase, I cannot speak fluently at all and I have grammar mistakes everywhere.
However, now when I try to type something in english, the german translation pops up in my mind first.
If I don't know the german, I have a problem writing it down in english.
As a result, my written english falls back to almost the same level as german.

* Ich kann nicht mich vorstellen

All my classmates come from diverse backgrounds.
At least 5 are Ukriainian, and at least 2 from some countries that I have never heard before.
English is no longer a universal language, but with my broken german I can barely chat.

Even with english, I have struggled a lot introducing myself.
In the past decade, I never had this issue since everyone around me shared the similar experience.
I can easily position myself; which education I had, which university I went, what work I am doing, what issue I have, etc.
But this coordinate system works no more in this class.
I am only confusing others if I mention I am a PhD student.
So you are a student, they ask, why would they pay a student?

Once I asked classmate what she does on weekend.
She paused, and said: because you are working, so the weekend is different for you, but I don't work, so there is no difference for me.
And before this I have never thought of such a bias in my question.

More and more often recently, I realize how limited my perspective is.
I did not know what the life with a social worker is like.
I did not know that Afghan can often speak Turkish.
I did not know what my lecture thinks when he works as a security guard at night.
I have been too much caught up in my own world, such that I am unable to ask a meaningful question of people I don't understand.
I want to know more about the difference of this world, but I don't know how.
